Repository canonical/operator-workflows, pull requests merged in 2023-12, with the labels that each got.

#222 Remove charmcraft cache system
  .github/workflows/build_charmcraft_cache.yaml
  .github/workflows/integration_test.yaml
  .github/workflows/workflow_charmcraft_cache_test.yaml
Labels: trivial

#221 Self hosted runner integration test
  .github/workflows/integration_test.yaml
  .github/workflows/integration_test_run.yaml
  .github/workflows/workflow_test.yaml
  README.md
  tests/workflows/integration/test-upload-charm/tox.ini
Labels: trivial

#223 Pass the inputs related to self-hosted runners through
  .github/workflows/integration_test.yaml
Labels: trivial

#225 fix(perms): Don't create labels
  .github/workflows/test.yaml
Labels: bug, urgent

#227 chore(github): Remove hotfix for perms
  .github/workflows/test.yaml
Labels: trivial

#229 Stop the Publish Charm workflow if no run-id could be retrieved
  .github/workflows/publish_charm.yaml
Labels: bug, trivial

#230 Upload charm artifact only if charm is present
  .github/workflows/integration_test.yaml
Labels: bug, trivial
