Repository canonical/operator-workflows, pull requests merged in 2024-12, with the labels that each got.

#494 Install reStructuredText parser required for vale
  .github/workflows/test.yaml
  tests/workflows/integration/test-upload-charm/docs/examples/test.rst
Labels: trivial

#491 Setting up allure for integration tests
  .github/workflows/allure_report.yaml
  .github/workflows/integration_test_run.yaml
  .github/workflows/workflow_test.yaml
  docs/how-to/integration_test_allure.md
  tests/workflows/integration/test-rock/requirements.txt
  tests/workflows/integration/test-upload-charm/requirements.txt
  tests/workflows/integration/test-upload-charm/tox.ini
Labels: enhancement, complex

#503 Update if conditions for Allure
  .github/workflows/allure_report.yaml
  .github/workflows/integration_test_run.yaml
Labels: trivial

#427 Add integration test secret environments
  .github/workflows/integration_test_run.yaml
Labels: trivial

#505 Exclude woke config from license checks
  .licenserc.yaml
Labels: trivial

#510 fix: ignore go trivy vuln in pebble
  tests/workflows/integration/test-rock/.trivyignore
Labels: bug, trivial
