Repository canonical/operator-workflows, pull requests merged in 2024-01, with the labels that each got.

#238 Bot pr approval
  .github/workflows/bot_pr_approval.yaml
  README.md
Labels: complex

#239 Debug info for bot approval PR
  .github/workflows/bot_pr_approval.yaml
Labels: trivial

#240 Fix name of the renovate bot actor
  .github/workflows/bot_pr_approval.yaml
Labels: trivial

#241 Use pagination in publish_charm
  .github/workflows/publish_charm.yaml
Labels: trivial

#242 Remove repo hardcoding
  .github/workflows/publish_charm.yaml
Labels: bug, trivial

#244 Fix name of bot
  .github/workflows/bot_pr_approval.yaml
Labels: trivial
