Repository canonical/operator-workflows, pull requests merged in 2025-01, with the labels that each got.

#518 Update Allure how-to doc
  .github/workflows/allure_report.yaml
  .github/workflows/auto_update_charm_libs.yaml
  .github/workflows/bot_pr_approval.yaml
  .github/workflows/comment.yaml
  .github/workflows/comment_contributing.yaml
  .github/workflows/integration_test.yaml
  .github/workflows/integration_test_run.yaml
  .github/workflows/jira.yaml
  .github/workflows/pr_from_template_files.yaml
  .github/workflows/promote_charm.yaml
  .github/workflows/publish_charm.yaml
  .github/workflows/run_bot_pr_approval.yaml
  .github/workflows/test.yaml
  .github/workflows/workflow_test.yaml
  docs/how-to/integration_test_allure.md
  src/build.ts
  src/model.ts
  src/plan-integration.ts
  src/plan-scan.ts
  src/plan.ts
  src/publish.ts
Labels: documentation, trivial

#524 Fix snap autorefresh
  .github/workflows/integration_test_run.yaml
Labels: trivial

#521 Correct how-to doc for Allure
  docs/how-to/integration_test_allure.md
Labels: documentation, trivial

#533 feat: Support for custom ubuntu series when selecting self-hosted runners in integration tests
  .github/workflows/integration_test.yaml
  .github/workflows/integration_test_run.yaml
Labels: trivial

#535 docs: document the feature to export secrets as environment variables
  README.md
Labels: documentation
